---
# defaults file for ocp4_workload_argocd_quay_todo-app

###
# ocp4_workload_gitea_operator/defaults/main.yml
###
become_override: false
ocp_username: system:admin
silent: false

ocp4_workload_gitea_user: user1
ocp4_workload_gitea_operator_create_admin: true
ocp4_workload_gitea_operator_create_users: true
ocp4_workload_gitea_operator_migrate_repositories: true
ocp4_workload_gitea_operator_gitea_image_tag: 1.19.3
ocp4_workload_gitea_operator_repositories_list:
- repo: "https://github.com/tosin2013/todo-demo-app-helmrepo.git"
  name: "todo-demo-app-helmrepo"
  private: false