- name: Deploy Quay Registry Operator
  k8s:
    definition: "{{ lookup('kubernetes.core.kustomize', dir='https://github.com/tosin2013/sno-quickstarts/gitops/cluster-config/quay-registry-operator/operator/overlays/stable-3.8') }}"
  register: quay_operator_result

- name: Deploy OpenShift Data Foundation Operator
  k8s:
    definition: "{{ lookup('kubernetes.core.kustomize', dir='https://github.com/tosin2013/sno-quickstarts/gitops/cluster-config/openshift-data-foundation-operator/operator/overlays/stable-4.11') }}"
  register: data_foundation_operator_result

- name: Wait for OpenShift Container Storage NooBaa deployment
  pause:
    seconds: 60

- name: Deploy OpenShift Container Storage NooBaa
  k8s:
    definition: "{{ lookup('kubernetes.core.kustomize', dir='https://github.com/tosin2013/sno-quickstarts/gitops/cluster-config/openshift-container-storage-noobaa/overlays/default') }}"
  register: container_storage_result

- name: Wait for OpenShift Container Storage NooBaa deployment
  pause:
    seconds: 120

- name: Deploy Quay Registry Operator Instance
  k8s:
    definition: "{{ lookup('kubernetes.core.kustomize', dir='https://github.com/tosin2013/sno-quickstarts/gitops/cluster-config/quay-registry-operator/instance/overlay/default') }}"

- name: Finished deploying Quay
  debug:
    msg: "Quay deployment completed successfully."