- name: Deploy Quay Registry Operator
  kubernetes.core.kustomize:
    state: present
    src: https://github.com/tosin2013/sno-quickstarts/gitops/cluster-config/quay-registry-operator/operator/overlays/stable-3.8
  register: quay_operator_result

- name: Wait for Quay Registry Operator deployment
  pause:
    seconds: 30
  when: quay_operator_result.rc == 0

- name: Deploy OpenShift Data Foundation Operator
  kubernetes.core.kustomize:
    state: present
    src: https://github.com/tosin2013/sno-quickstarts/gitops/cluster-config/openshift-data-foundation-operator/operator/overlays/stable-4.11
  register: data_foundation_operator_result

- name: Wait for OpenShift Data Foundation Operator deployment
  pause:
    seconds: 30
  when: data_foundation_operator_result.rc == 0

- name: Deploy OpenShift Container Storage NooBaa
  kubernetes.core.kustomize:
    state: present
    src: https://github.com/tosin2013/sno-quickstarts/gitops/cluster-config/openshift-container-storage-noobaa/overlays/default
  register: container_storage_result

- name: Wait for OpenShift Container Storage NooBaa deployment
  pause:
    seconds: 120
  when: container_storage_result.rc == 0

- name: Deploy Quay Registry Operator Instance
  kubernetes.core.kustomize:
    state: present
    src: https://github.com/tosin2013/sno-quickstarts/gitops/cluster-config/quay-registry-operator/instance/overlay/default

- name: Finished deploying Quay
  debug:
    msg: "Quay deployment completed successfully."