---
# Implement your Workload removal tasks here

- name: Remove GitOps
  k8s:
    definition: "{{ lookup('kubernetes.core.kustomize', dir='https://github.com/tosin2013/sno-quickstarts/gitops/cluster-config/openshift-gitops') }}"
    state: absent
  vars:
    ACTION: remove

- name: Remove Quay Registry Operator Instance
  k8s:
    definition: "{{ lookup('kubernetes.core.kustomize', dir='https://github.com/tosin2013/sno-quickstarts/gitops/cluster-config/quay-registry-operator/instance/overlay/default') }}"
    state: absent
  vars:
    ACTION: remove

- name: Remove Quay Registry Operator
  k8s:
    definition: "{{ lookup('kubernetes.core.kustomize', dir='https://github.com/tosin2013/sno-quickstarts/gitops/cluster-config/quay-registry-operator/operator/overlays/stable-3.8') }}"
    state: absent
  vars:
    ACTION: remove

#- name: Remove OpenShift Container Storage NooBaa
#  k8s:
#    definition: "{{ lookup('kubernetes.core.kustomize', dir='https://github.com/tosin2013/sno-quickstarts/gitops/cluster-config/openshift-container-storage-noobaa/overlays/default') }}"
#    state: absent
#  vars:
#    ACTION: remove

- name: Remove Pipelines
  ansible.builtin.include_role:
    name: ocp4_workload_pipelines
  vars:
    ACTION: remove

- name: Remove Gitea Operator
  ansible.builtin.include_role:
    name: ocp4_workload_gitea_operator
  vars:
    ACTION: remove


# Leave this as the last task in the playbook.
- name: remove_workload tasks complete
  debug:
    msg: "Remove Workload tasks completed successfully."
  when: not silent | bool
