---
# Implement your Workload deployment tasks here

- name: Install OpenShift Gitops
  k8s:
    definition: "{{ lookup('kubernetes.core.kustomize', dir='https://github.com/tosin2013/sno-quickstarts/gitops/cluster-config/openshift-gitops') }}"
    state: present
  register: openshift_gitops_result
  ignore_errors: true

- name: Install Gitea
  ansible.builtin.include_role:
    name: ocp4_workload_gitea_operator

#- name: Install OpenShift Pipelines
#  ansible.builtin.include_role:
#    name: ocp4_workload_pipelines

- name: Install and Deploy Quay
  include_tasks: quay-deployment.yml


#- name: Install GitOps
#  ansible.builtin.include_role:
#    name: ocp4_workload_openshift_gitops

#- name: Set gitea route
#  set_fact:
#    ocp4_workload_argocd_quay_todo_app_gitea_route: "{{ r_gitea.resources[0].status.giteaRoute }}"

#- name: Set gitea repo url
#  set_fact:
#    ocp4_workload_argocd_quay_todo_app_gitea_repo_url: "{{ ocp4_workload_argocd_quay_todo_app_gitea_route }}/{{ ocp4_workload_gitea_aiml_user }}/gitops.git"

#- name: Install Gitops Repo Secret
#  kubernetes.core.k8s:
#    state: present
#    merge_type:
#      - strategic-merge
#      - merge
#    definition: "{{ lookup('template', './templates/gitops-repo-secret.yml.j2') }}"


# Leave this as the last task in the playbook.
- name: workload tasks complete
  debug:
    msg: "Workload Tasks completed successfully."
  when: not silent